export { endpointRequiresAuth } from "./auth.js";
export {
  VALID_DOMAINS,
  type AuthStrategy,
  type CapabilityDefinition,
  type CompactEndpoint,
  type Domain,
  type EndpointFieldRef,
  type EndpointParameter,
  type EndpointRequestBody,
  type EndpointResponseSchema,
  type FullEndpoint,
  type GeneratedProjectManifest,
  type GenerationPlan,
  type OutputMode,
  type PlanConfidence,
  type PlanWarning,
  type SchemaConnection,
  type SchemaConnectionConfidence,
  type SearchResult,
  type SuggestionConfidence,
  type SuggestionResult,
  type ValidationReport,
  type WorkflowDefinition,
  type WorkflowInputMapping,
  type WorkflowStepDefinition,
} from "./types.js";
